name: Build MarshalSec

on:
  workflow_dispatch:  # 手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up JDK 1.8
      uses: actions/setup-java@v4.5.0
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: 1.8
        
    - name: Build with Maven
      run: |
        mvn clean package -DskipTests
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: marshalsec
        path: target/marshalsec-*.jar
